version: "3.8"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - ./test_schema.sql:/docker-entrypoint-initdb.d/schema.sql 